/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.main.java.demo;
import java.io.IOException;
import java.net.MalformedURLException;
import java.lang.InterruptedException;


public class App {
    public void getGreeting() throws InterruptedException, IOException, MalformedURLException {
        System.out.println("Hello");
        TestCases tests = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here
        // tests.testCase01();
        // tests.nestedFramesText();
        // tests.searchAmazon();
        tests.countHyperlinks();

        //END Tests
        tests.endTest();// End your test by clearning connections and closing browser
        System.out.println("Task completed sucessfully");
    }

    public static void main(String[] args) throws InterruptedException, IOException, MalformedURLException {
        new App().getGreeting();
    }
}
